grpc:
  port: 8084
  timeout: 50000 # in nanoseconds

router:
  password: admin
  
log.prefix: RAS Client controller

auth.key: "CoolAuthKeyThat needs to be changed"

server:
  port: 8080
  mode: release
  
storage:
  path: /tmp/router-key-value-storage
  

system:
  default-password: admin

client:
  address: http://localhost:5173
